version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    depends_on:
      - web-server
      - authentication
      - player-management
      - chat
      - webrtc-signaling
    networks:
      - backend

  web-server:
    build:
      context: ./services/web-server
      dockerfile: Dockerfile
    ports:
      - "3000:8000"
    volumes:
      - ./services/web-server/public:/usr/src/app/public
    networks:
      - backend
    environment:
      DB_USER: user
    env_file:
      - .env

  authentication:
    build:
      context: ./services/authentication
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production
    env_file:
      - .env
    networks:
      - backend

  webrtc-signaling:
    build:
      context: ./services/webrtc-signaling
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    networks:
      - backend

  chat:
    build:
      context: ./services/chat
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      NODE_ENV: production
    env_file:
      - .env
    networks:
      - backend

  game-logic:
    build:
      context: ./services/game-logic
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    environment:
      NODE_ENV: production
    env_file:
      - .env
    networks:
      - backend

  player-management:
    build:
      context: ./services/player-management
      dockerfile: Dockerfile
    ports:
      - "8004:8000"
    environment:
      NODE_ENV: production
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - player_data:/usr/src/app/data

networks:
  backend:
    driver: bridge

volumes:
  player_data:
